# Generated by Django 4.1.4 on 2023-03-01 03:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booktest', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='bookinfo',
            table='tb_books',
        ),
    ]
