# Generated by Django 4.1.4 on 2023-03-09 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booktest', '0003_alter_bookinfo_options_heroinfo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookinfo',
            old_name='ncomment',
            new_name='bcomment',
        ),
    ]
